server:
  port: 80

spring:
  data:
    mongodb:
      uri: mongodb://lhy:123456@localhost:27017/java

## 设置接收文件的大小
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=20MB